# main.yml
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Include Frontend Role
      include_role:
        name: frontend
      tags:
        - frontend

    - name: Include Web App Role
      include_role:
        name: web_app
      tags:
        - web_app

    - name: Start Frontend Container
      command: docker run -d -p "{{ frontend_port }}:80" -v "{{ role_path }}/frontend/files:/usr/share/nginx/html" nginx
      tags:
        - frontend

    - name: Pull Web App Container Image
      command: docker pull "{{ web_app_image }}"
      tags:
        - web_app

    - name: Start Web App Container
      command: docker run -d -p 8080:80 "{{ web_app_image }}"
      tags:
        - web_app