---
- name: ip3 Ansible playbook
  hosts: all
  become: yes
  tasks:
    - name: ensure ntpd is at the latest version
      apt: pkg=ntp state=latest update_cache=yes
      become: yes
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
      become: yes

    - name: Run Docker container
      docker_container:
       name: ip2backend-docker
       image: ip2backend-docker
       state: started 

    - name: Ensure docker is started
      become: yes
      ansible.builtin.systemd:
        service: docker
        state: started