---
- name: ip3 Ansible playbook
  hosts: all
  become: yes
  tasks:
    - name: ensure ntpd is at the latest version
      apt: pkg=ntp state=latest update_cache=yes
      become: yes
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
      become: yes