---
- name: Apache server installed
  hosts: all
  become: yes
  tasks:
  - name: latest Apache version installed
    ansible.builtin.yum:
      name: httpd
      state: latest
  - name: Apache enabled and running
    ansible.builtin.service:
      name: httpd
      enabled: true
      state: started