# roles/frontend/tasks/main.yml
- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Copy index.html to the NGINX web root
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
